version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ignablog:/var/www/html/fp-content/

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ignablog:/var/www/html/fp-content

networks:
  internal:
    driver: bridge

volumes:
  ignablog:
